"""make description order_number days_count nullable

Revision ID: 6441b99cf580
Revises: 0f6ea8cfb23f
Create Date: 2026-09-20 22:02:56.302212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6441b99cf580'
down_revision: Union[str, Sequence[str], None] = '0f6ea8cfb23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('periods', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('periods', 'order_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('periods', 'days_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('periods', 'days_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('periods', 'order_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('periods', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
